version: "3.9"
services:
  poa-backend:
    container_name: poa-backend
    restart: unless-stopped
    build:
      context: ./poa-backend
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - '443:5000'
    environment:
      - MONGODB_URI=mongodb+srv://Asa:FavRwReB2lnuleS9@cluster0.u8vwe.mongodb.net/?retryWrites=true&w=majority
      - MONGODB_USER=Asa
      - MONGODB_PASSWORD=FavRwReB2lnuleS9

  poa-frontend:
    depends_on:
      - poa-backend
    container_name: poa-angular
    build:
      context: ./poa-front-end
      dockerfile: Dockerfile
    ports:
      - '8888:80'
    volumes:
      - './Dockerfile:/usr/src/app'

volumes:
  poa:
